add-highlighter global/ wrap -word -indent

set global ui_options ncurses_set_title=false ncurses_assistant=off ncurses_enable_mouse=false
set global autoinfo ''
set global autocomplete ''

def find -params 1 -shell-script-candidates %{ find . -type f } %{ edit %arg{1} }

# def git-find -params 1 -shell-script-candidates %{ git ls-files } %{ edit %arg{1} }
# def fd -params 1 -shell-script-candidates %{ fd . -t f } %{ edit %arg{1} }

map global user w ': w<ret>'
map global user d ': db<ret>'
map global user q ': q<ret>'

map global user b ': b '
map global user f ': find '

map global user p ': nop %sh{ groff "$kak_buffile" -ms -Tpdf > $(basename "$kak_buffile" .ms).pdf }<ret>'

map global normal '#' :comment-line<ret>
map global normal '<a-#>' :comment-block<ret>

# https://github.com/mawww/kakoune/issues/2108

define-command sleuth -docstring 'Heuristically set buffer options' %{
  try %{
    evaluate-commands -draft %{
      # Search the first indent level
      execute-keys 'gg' '/' '^\h+' '<ret>'

      # Tab vs. Space
      # https://youtu.be/V7PLxL8jIl8
      try %{
        execute-keys '<a-k>' '\t' '<ret>'
        set-option buffer indentwidth 0
      } catch %{
        set-option buffer indentwidth %val{selection_length}
      }
    }
  }
}

# Run sleuth when opening files.
hook -group sleuth global BufOpenFile .* %{
  sleuth
}
