add-highlighter global/ wrap -word -indent

set global ui_options ncurses_set_title=false ncurses_assistant=off ncurses_enable_mouse=false
set global autoinfo ''
set global autocomplete ''

def find -params 1 -shell-script-candidates %{ find . -type f } %{ edit %arg{1} }

def git-edit -params 1 -shell-script-candidates %{ git ls-files } %{ edit %arg{1} }

map global user <space> ':git-edit '

map global normal '#' :comment-line<ret> -docstring 'comment line'
map global normal '<a-#>' :comment-block<ret> -docstring 'comment block'
