#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -cursor_name left_ptr &
xset s off &
xset -dpms &
setxkbmap -option ctrl:nocaps &
nitrogen --restore &
/home/a2lqr4/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap          10
# bspc config top_padding         30

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color  \#484848
bspc config focused_border_color \#FFFFFF
bspc config urgent_border_color \#B58900
bspc config presel_border_color \#000000

bspc rule -a Emacs state=tiled
